# Generated by Django 4.1.5 on 2024-03-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp_app", "0002_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="is_admin", field=models.BooleanField(default=True),
        ),
    ]
